apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - postgres-replica.yaml
  - redis.yaml
  - garage.yaml
  - smtp-listener.yaml
  - api.yaml
  - client.yaml
  - website.yaml
  - cloudflared.yaml
